enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 4
patches-version = "latest" # 'latest', 'dev', or a version number. default: "latest"
cli-version = "latest"       # 'latest', 'dev', or a version number. default: "latest"


#[Music-Extended]
enabled=false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "arm64-v8a"
#version = "latest"
version = "8.15.52"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
#patches-version = "v5.9.1-dev.5"
included-patches = ""
excluded-patches = "'Certificate spoof' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom branding icon MMT' 'Custom branding icon Revancify Blue' 'Custom branding icon Revancify Red' 'Custom branding icon YouTube Music' 'Custom branding icon YouTube Music' 'Custom playback speed' 'Enable custom filter' 'Enable old style library shelf' 'Enable old style miniplayer' 'Enable zen mode' 'Hide category bar' 'Hide new playlist button' 'Hide playlist card' 'Hide radio button' 'Remember playback speed' 'Replace dismiss queue' 'Return YouTube Dislike' 'SponsorBlock' 'Translations'"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[YouTube-Extended]
Enable=true
app-name = "YouTube"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "RVX-kotaro311"
build-mode = "module"
module-prop-name = "RVX-kotaro311"
#version = "auto"
version = "19.16.39"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
excluded-patches = "'Custom branding name for YouTube' 'Swipe controls'"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=mmt -e 'Theme' -OlightThemeBackgroundColor=@android:color/white -OdarkThemeBackgroundColor=@android:color/black"

